 const SignupAction=(dispatch)=>{
     return{
         changeName:(value)=>dispatch({
             type:"name",
             about:"signupForm",
             prop:value
         }),
         changeEmail:(value)=>dispatch({
             type:"email",
             about:"signupForm",
             prop:value
         }),
         changePassword:(value)=>dispatch({
             type:"password",
             about:"signupForm",
             prop:value
         }),
         changeCollege:(value)=>dispatch({
             type:"college",
             about:"signupForm",
             prop:value
         }),
         changeProfession:(value)=>dispatch({
             type:"profession",
             about:"signupForm",
             prop:value
         }),
        passwordError:(value)=>dispatch({
            type:"password",
            about:"signupError",
            prop:value
        }),
        emailError:(value)=>dispatch({
            type:"email",
            about:"signupError",
            prop:value
        }),
        changeOtpType:(value)=>dispatch({
            type:"signup",
            prop:value
        }),
        changeFetching:(value)=>dispatch({
            type:"isFetching",
            prop:value
        })
     }
 }
 export default SignupAction;